### ISSUE TITLE
nsp_pantry.json file is missing

### ISSUE THREAD

**Issue by Nechochwen-D** [omar92/ComfyUI-QualityOfLifeSuit_Omar92#10]
The `nsp_pantry.json` file is missing or is not being generated when it is run and subsequently breaks the whole UI.

**Comment by wyrde** [comment]
I'm not able to replicate this. I've tried 4 different versions and all downloaded NSP fine.

Are you using the git version, download from civit? Have you git pulled to update? More info is needed.

**Comment by Ishino** [comment]
Starting from the git version, when you start ComfyUI, it generates the config.json, but not nsp_pantry.json

**Comment by Ishino** [comment]
it appears when you add an OpenAPI node, which was a bit confusing

**Comment by nckgriva** [comment]
```
# region global
NODE_FILE = os.path.abspath(__file__)
SUIT_DIR = (os.path.dirname(os.path.dirname(NODE_FILE))
            if os.path.dirname(os.path.dirname(NODE_FILE)) == 'QualityOfLifeSuit_Omar92'
            or os.path.dirname(os.path.dirname(NODE_FILE)) == 'QualityOfLifeSuit_Omar92-dev'
            else os.path.dirname(NODE_FILE))
SUIT_DIR = SUIT_DIR+"\\.."
```
this code will generate a path that will only work on Windows

**Comment by shadownetdev1** [comment]
I changed it to:

```
# region global
NODE_FILE = os.path.abspath(__file__)
SUIT_DIR = (os.path.dirname(os.path.dirname(NODE_FILE))
            if os.path.dirname(os.path.dirname(NODE_FILE)) == 'QualityOfLifeSuit_Omar92'
            or os.path.dirname(os.path.dirname(NODE_FILE)) == 'QualityOfLifeSuit_Omar92-dev'
            else os.path.dirname(NODE_FILE))
SUIT_DIR = SUIT_DIR+"/.."
```
And it seems to work for me on Ubuntu.
Ideally it would be cross platform. Potentially using platform.system() to figure out what OS it is running on.

**Comment by Marus** [comment]
on macOS this will generate a bad path.

What you should be using for that final line in that block should be

`SUIT_DIR = os.path.normpath(os.path.join(SUIT_DIR, '..'))`

You pretty much should always use os.path calls for any path manipulation to ensure they are platform independent

**Comment by Marus** [comment]
I created PR #11 to fix the issue in the repo.

**Comment by wyrde** [comment]
thanks, dude!
