### ISSUE TITLE
I want to use it, but I can't use it, the author helps me

### ISSUE THREAD

**Issue by koala-cg** [omar92/ComfyUI-QualityOfLifeSuit_Omar92#12]
There is no schematic diagram. Although I know the introduction of each function, how to connect them in series?
I hope the author can give some schematic diagrams of how to use it

**Comment by Piscabo** [comment]
There is workflows, but they not working for me?
![image](https://github.com/omar92/ComfyUI-QualityOfLifeSuit_Omar92/assets/123719842/c522d2ea-099b-4bf8-9852-b402a61c8edd)
