### ISSUE TITLE
Failed to auto update `Quality of Life Suit`

### ISSUE THREAD

**Issue by wangwenqiao666** [omar92/ComfyUI-QualityOfLifeSuit_Omar92#28]
Your __init__.py file has an error on line 34:
"from .update import update as update " should be changed to "from .Update import update as update ".
![image](https://github.com/omar92/ComfyUI-QualityOfLifeSuit_Omar92/assets/55267900/7fbb6dc6-f565-4194-92de-8a71f5deea0d)

**Comment by C2PO-Production** [comment]
Thanks, that seems to have fixed my update problem.
