### ISSUE TITLE
readme.md refers to wrong file for api key

### ISSUE THREAD

**Issue by wyrde** [omar92/ComfyUI-QualityOfLifeSuit_Omar92#5]
Is there any particular formatting required for the api_key.txt file?
The following error is thrown

`Error: OpenAI API key is invalid OpenAI features wont work for you`

I made a file with that name and dropped my key into it, but it gives this error. Key generated at https://platform.openai.com/account/api-keys

**Comment by wyrde** [comment]
Ah! SAmira cleared it up!

The line in readme.md that says `Once you have your API key, add it to the api_key.txt file` needs to be changed to `config.json` file.

**Comment by omar92** [comment]
oh thanks , sorry forgot it

**Comment by omar92** [comment]
fixed that on dev
