### ISSUE TITLE
[Bug] ImageScaleFactor __O node seems to be flipping X Y axis

### ISSUE THREAD

**Issue by wyrde** [omar92/ComfyUI-QualityOfLifeSuit_Omar92#9]
The image scale factor node is flipping the Height Width values with each use.

![flipped xy](https://user-images.githubusercontent.com/9657443/230795729-d2499da0-0831-4de4-bbcb-c682292f9169.png)
```
got prompt
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:06<00:00,  1.25s/it]
QualityOfLifeSuit_Omar92::upscale from (768,512) to (1536,1024)
QualityOfLifeSuit_Omar92::upscale from (1024,1536) to (512,768)
QualityOfLifeSuit_Omar92::upscale from (768,512) to (1536,1024)
```
![ComfyUI_00239_](https://user-images.githubusercontent.com/9657443/230795801-ed8547aa-e8b6-40f1-8cdd-55e7335bf6cb.png)
![ComfyUI_00240_](https://user-images.githubusercontent.com/9657443/230795800-ef344af9-a8dd-43fe-8d36-fe1669172bd3.png)
![ComfyUI_00241_](https://user-images.githubusercontent.com/9657443/230795797-f532eb13-3b65-4e7e-a5cf-864e031a1191.png)
![ComfyUI_00242_](https://user-images.githubusercontent.com/9657443/230795795-e000023a-fcf5-48d9-9249-8fabf7a7faeb.png)

**Comment by omar92** [comment]
Thanks so much, fixed that

**Comment by omar92** [comment]
it is rotating the images now XD

**Comment by omar92** [comment]
kindly test now and tell me if the problem still happen

**Comment by wyrde** [comment]
Hi. Did you commit the changes? Is it another branch? I'm not getting an update with git pull

**Comment by omar92** [comment]
yea i commited

**Comment by omar92** [comment]
so weird , but thanks so much for the help
